# Generated by Django 5.2.5 on 2025-09-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobadvert',
            old_name='comapany_name',
            new_name='company_name',
        ),
    ]
