# Generated by Django 5.2.5 on 2025-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('candidate', 'Candidate')], default='candidate', max_length=10),
        ),
    ]
