# Generated by Django 5.2.5 on 2025-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('candidate', 'Candidate')], default='candidate', max_length=10),
        ),
    ]
