# Generated by Django 5.2.5 on 2025-10-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendinguser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('candidate', 'Candidate')], default='candidate', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('candidate', 'Candidate')], default='candidate', max_length=10),
        ),
    ]
